hub:
  image:
    name: jhfoo
  extraConfig:
    mck.py: |
      import mck_init
      mck_init.init_mck_secrets(c)
custom:
  hub_cookie_secret: "mck://cookie_secret"
proxy:
  secretToken: "mck://placeholder"
singleuser:
  extraEnv:
    MCK_JUP_CLIENT_ID: "mck://jup_client_id"



